name: NoItemExplode
version: '${project.version}'
main: me.kirkfox.noitemexplode.NoItemExplode
api-version: 1.13
author: Kirk Fox
description: A plugin that can disable the destruction of items by explosions within a world
commands:
  noitemexplode:
    description: Set whether or not NoItemExplode protects the current world from items being exploded
    usage: /nie <on|off>
    aliases: nie
    permission: noitemexplode.view
permissions:
  noitemexplode.set.*:
    default: op
    children:
      noitemexplode.set.world: true
      noitemexplode.set.chunk: true
  noitemexplode.set.world:
    default: op
    children:
      noitemexplode.view: true
  noitemexplode.set.chunk:
    default: op
    children:
      noitemexplode.view: true
  noitemexplode.view:
    default: op